# Generated by Django 4.2.1 on 2023-06-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='background_color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
