# Generated by Django 4.2.1 on 2023-06-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_author_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_social',
            field=models.BooleanField(default=False),
        ),
    ]
